### ISSUE TITLE
Linux run error

### ISSUE THREAD

**Issue by Claus1** [gskinnerTeam/flutter-folio#27]
Mint 19.1 x86 binaries from the site.
Clean gray screen and output in the console:
```
flutter: firestore-DART Initialized
flutter: Bootstrap Started, v1.0.0-RC6
flutter: Loading file @ /home/george/.local/share/flutterfolio/app-model
flutter: FileSystemException: Cannot open file, path = '/home/george/.local/share/flutterfolio/app-model' (OS Error: No such file or directory, errno = 2)
flutter: Failed to decode save file json: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
flutter: File loaded, Rect.fromLTRB(0.0, 0.0, 0.0, 0.0)
flutter: UnimplementedError: appWindow has not been implemented.
flutter: #0      BitsdojoWindowPlatform.appWindow (package:bitsdojo_window_platform_interface/bitsdojo_window_platform_interface.dart:45)
flutter: #1      appWindow (package:bitsdojo_window/src/app_window.dart:44)
flutter: #2      LinuxTitleBar.build (package:flutter_folio/_utils/native_window_utils/titlebar_wrappers/linux_title_bar.dart:39)
flutter: #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4661)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4587)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566)
flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561)
flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3623)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3378)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566)
flutter: #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561)
flutter: #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3623)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3378)
flutter: #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5653)
flutter: #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6197)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #21     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6073)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #27     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #31     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #39     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #41     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5595)
flutter: #42     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6197)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #45     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #46     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #47     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #50     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #51     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #54     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #55     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #56     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6073)
flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #61     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #62     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #63     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6073)
flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #67     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #68     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #69     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #70     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #72     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #73     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #74     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #77     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #78     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #79     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #81     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #82     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #83     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #85     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5595)
flutter: #86     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6197)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #89     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #90     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #91     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #93     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #94     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #95     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #97     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #98     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #99     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
```

**Comment by vially** [comment]
I'm experience the same issue on Arch Linux (binaries from the site) using Wayland (not sure if it's relevant though).

**Comment by ErinMyLungs** [comment]
Same with ubuntu 18.04 LTS with x11 - it looks like it tries to open a json file that doesn't exist and just crashes.

Maybe a solution would be to check if exists and if not load defaults/create file before launch?

<details>
<summary>Crash log dump</summary>
```
flutter: firestore-DART Initialized
flutter: Bootstrap Started, v1.0.0-RC6
flutter: Loading file @ /home/erin/.local/share/flutterfolio/app-model
flutter: FileSystemException: Cannot open file, path = '/home/erin/.local/share/flutterfolio/app-model' (OS Error: No such file or directory, errno = 2)
flutter: Failed to decode save file json: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
flutter: File loaded, Rect.fromLTRB(0.0, 0.0, 0.0, 0.0)
flutter: UnimplementedError: appWindow has not been implemented.
flutter: #0      BitsdojoWindowPlatform.appWindow (package:bitsdojo_window_platform_interface/bitsdojo_window_platform_interface.dart:45)
flutter: #1      appWindow (package:bitsdojo_window/src/app_window.dart:44)
flutter: #2      LinuxTitleBar.build (package:flutter_folio/_utils/native_window_utils/titlebar_wrappers/linux_title_bar.dart:39)
flutter: #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4661)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4587)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566)
flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561)
flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3623)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3378)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566)
flutter: #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561)
flutter: #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3623)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3378)
flutter: #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5653)
flutter: #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6197)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #21     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6073)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #27     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #31     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #39     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #41     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5595)
flutter: #42     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6197)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #45     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #46     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #47     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #50     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #51     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #54     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #55     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #56     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6073)
flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #61     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #62     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #63     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6073)
flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #67     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #68     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #69     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #70     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #72     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #73     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #74     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #77     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #78     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #79     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #81     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #82     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #83     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #85     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5595)
flutter: #86     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6197)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #89     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #90     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #91     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #93     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #94     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #95     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #97     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #98     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #99     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
```
</details>

**Comment by ErinMyLungs** [comment]
Okay I spent a minute trying to debug and here's some info:

### Missing Local File:
* There should be a json at `~/.local/share/flutterfolio/app-model` to load
* Creating a json file (example below) solves this error but a new one appears

<details>
<summary>app-model example file</summary>

``` JSON
{
  "currentUser":null,
  "winX": 0.0,
  "winY": 0.0,
  "winWidth": 600.0,
  "winHeight": 600.0,
  "enableTouchMode": false
}
```
</details>

## Actual Issue

### Summary
Bitsdojo Window package does not support linux yet, throws a unimplemented error and causes the app to fail.

* Note in the [package repo](https://github.com/bitsdojo/bitsdojo_window#bitsdojo_window) before getting started they say that linux support is a future goal, not currently working
* It calls out [linux_title_bar.dart](https://github.com/gskinnerTeam/flutter-folio/blob/master/lib/_utils/native_window_utils/titlebar_wrappers/linux_title_bar.dart) as the project error source during the build


### Details

<details>
<summary>Crash log with UnimplementedError</summary>

Note `flutter: #0` is the specific error

```
flutter: firestore-DART Initialized
flutter: Bootstrap Started, v1.0.0-RC6
flutter: Loading file @ /home/lego/.local/share/flutterfolio/app-model
flutter: File loaded, Rect.fromLTRB(0.0, 0.0, 600.0, 600.0)
flutter: UnimplementedError: appWindow has not been implemented.
flutter: #0      BitsdojoWindowPlatform.appWindow (package:bitsdojo_window_platform_interface/bitsdojo_window_platform_interface.dart:45)
flutter: #1      appWindow (package:bitsdojo_window/src/app_window.dart:44)
flutter: #2      LinuxTitleBar.build (package:flutter_folio/_utils/native_window_utils/titlebar_wrappers/linux_title_bar.dart:39)
flutter: #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4661)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4587)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566)
flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561)
flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3623)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3378)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566)
flutter: #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561)
flutter: #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3623)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3378)
flutter: #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5653)
flutter: #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6197)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #21     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6073)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #27     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #31     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #39     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #41     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5595)
flutter: #42     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6197)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #45     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #46     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #47     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #50     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #51     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #54     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #55     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #56     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6073)
flutter: #59     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #61     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #62     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #63     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6073)
flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #67     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #68     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #69     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #70     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #72     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #73     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #74     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #77     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #78     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #79     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #81     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #82     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #83     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #85     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5595)
flutter: #86     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6197)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #89     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #90     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #91     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #93     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #94     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #95     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #97     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #98     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #99     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
```
</details>

## Possible Solutions?

### app-model missing file
This should be a quick-ish fix in [app_model.dart](https://github.com/gskinnerTeam/flutter-folio/blob/master/lib/models/app_model.dart)
* update `load` method line 121 to try catch file not found error

It'll load fine with an empty file so maybe on parse failure or no file create a default app-model and use `toJson` and `save` to fix this issue after first run.

### Bitdojo

This is harder. You could try to tear out the bitdojo specific code and have a linux-specific window customization use some other method.

* [lib/_utils/native_window_utils/window_utils_native.dart](https://github.com/gskinnerTeam/flutter-folio/blob/master/lib/_utils/native_window_utils/window_utils_native.dart) update the output for `Platform.isLinux` conditional branch
* [lib/_utils/native_window_utils/titlebar_wrappers/linux_title_bar.dart](https://github.com/gskinnerTeam/flutter-folio/blob/master/lib/_utils/native_window_utils/titlebar_wrappers/linux_title_bar.dart) Pull out bitdojo appWindow usage.

Honestly it's super disappointing this got through because it feels like something that should have been caught running the build on a linux box the first time.

**Comment by esDotDev** [comment]
Thanks everyone, we're currently looking into this. As mentioned we have a custom fork of bitsdojo we're looking to merge, at that point hopefully this will clear up.

The save file is a bit of a red herring, it's expected that on first launch there is nothing to load, and we're just printing this error. Will remove that so there's less confusion.
